language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-mobbit' ]; then cd .. && eval "mv $currentfolder generator-mobbit" && cd generator-mobbit; fi
